# Generated by Django 5.2.5 on 2025-08-16 16:04

from django.db import migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_birth_customer_date_of_birth_alter_user_id_and_more'),
    ]

    operations = [
          migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(null=True, blank=True),
        ),
    ]
