# Generated by Django 5.2.5 on 2025-08-17 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AddField(
            model_name='service',
            name='request_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='address',
            field=models.CharField(default='Not provided', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='hours',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='services.service'),
        ),
    ]
